SELECT TRAINING.*, STUDENT_HAS_TRAING.IdTraining, STUDENT_HAS_TRAING.IdStudent, STUDENT.IdStudent, STUDENT.Name
FROM TRAINING
INNER JOIN STUDENT_HAS_TRAING
ON TRAINING.IdTraining = STUDENT_HAS_TRAING.IdTraining
INNER JOIN STUDENT
ON STUDENT.IdStudent = STUDENT_HAS_TRAING.IdStudent
WHERE STUDENT.IdStudent = 6;


SELECT * FROM LOGIN;


SELECT TRAINING.Name, STUDENT_HAS_TRAING.IdTraining, STUDENT_HAS_TRAING.IdStudent, STUDENT.Name, CHALLENGE.*
FROM TRAINING
INNER JOIN STUDENT_HAS_TRAING
ON STUDENT_HAS_TRAING.IdTraining = TRAINING.IdTraining
INNER JOIN STUDENT
ON STUDENT.IdStudent = STUDENT_HAS_TRAING.IdStudent
INNER JOIN CHALLENGE
ON CHALLENGE.IdChallenge = STUDENT_HAS_TRAING.IdChallenge
WHERE STUDENT.IdStudent = 4 AND CHALLENGE.IdChallenge > 1;


select LOGIN.UserRG, LOGIN.IdAcessPermission, ACCESS_PERMISSION.*
from LOGIN
inner JOIN ACCESS_PERMISSION
ON LOGIN.IdAcessPermission = ACCESS_PERMISSION.IdAcessPermission
WHERE LOGIN.UserRG = 987654321;

