select LOGIN.UserRG, LOGIN.IdAcessPermission, ACCESS_PERMISSION.IdAcessPermission, ACCESS_PERMISSION.Description, COACH.Name, COACH.RG
from LOGIN
inner JOIN ACCESS_PERMISSION
ON LOGIN.IdAcessPermission = ACCESS_PERMISSION.IdAcessPermission
inner JOIN COACH
ON COACH.RG = LOGIN.UserRG
WHERE LOGIN.UserRG = 948380;


select STUDENT.Name, STUDENT.RG, LOGIN.UserRG
from STUDENT
inner JOIN LOGIN
ON STUDENT.RG = LOGIN.UserRG
WHERE LOGIN.UserRG = 98804200;

